name: scalajs-reaction
baseurl: /scalajs-reaction
description: A react integration library for scala.js in the spirit of ReasonReact
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1.0-M7
org: ttg
markdown: kramdown
