name: CI - simple compile
on: [workflow_dispatch]
jobs:
  build:
    strategy:
        fail-fast: false
        matrix:
         os: [ubuntu-latest]
         scala: ["2.13.3"]
         java: [ "openjdk@1.14"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
    - uses: olafurpg/setup-scala@v10
      with:
        java-version: ${{ matrix.java }} 
    - name: Compile
      run: sbt compile 
